# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 11:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_pgjson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=100)),
                ('params', django_pgjson.fields.JsonField(blank=True, default={})),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('event_type', models.SmallIntegerField(choices=[(b'Tournament', b'Tournament'), (b'Ladder', b'Ladder')])),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('rating_algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Algorithm')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_control', models.CharField(max_length=25)),
                ('result', models.SmallIntegerField(choices=[(b'1-0', b'1-0'), (b'0-1', b'0-1'), (b'1/2-1/2', b'1/2-1/2')])),
                ('date', models.DateField(blank=True, null=True)),
                ('round', models.SmallIntegerField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(b'public', b'public'), (b'private', b'private')])),
                ('eco', models.CharField(blank=True, max_length=50, null=True)),
                ('pgn', models.CharField(blank=True, max_length=2500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_student_member', models.NullBooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='black',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black', to='club.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Event'),
        ),
        migrations.AddField(
            model_name='game',
            name='white',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white', to='club.Player'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('player', 'event')]),
        ),
    ]
