# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 18:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_pgjson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('method', models.CharField(help_text='The name of the method used in rating_algs.py', max_length=30, null=True)),
                ('params', django_pgjson.fields.JsonBField(blank=True, default={})),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white_rating', models.IntegerField(blank=True, null=True)),
                ('black_rating', models.IntegerField(blank=True, null=True)),
                ('time_control', models.CharField(blank=True, max_length=25, null=True)),
                ('result', models.SmallIntegerField(choices=[(0, '1-0'), (1, '0-1'), (2, '1/2-1/2')])),
                ('datetime', models.DateTimeField(auto_now_add=True, help_text='NOTE: game time MUST be sufficient to place it in sufficiently correct chronological order with other games.', null=True)),
                ('round', models.SmallIntegerField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'public'), (1, 'private')], default=0)),
                ('eco', models.CharField(blank=True, max_length=50, null=True)),
                ('pgn', models.CharField(blank=True, max_length=2500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ladder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ladder_type', models.SmallIntegerField(blank=True, choices=[(0, 'ladder'), (1, 'tournament')], null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('inactivity_period', models.IntegerField(blank=True, help_text="After this many days without a game, the player's ranking will drop by demotion_inc places.", null=True)),
                ('demotion_inc', models.IntegerField(blank=True, help_text="When the inactivity penalty is enforced, the player's ranking falls this many places", null=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Algorithm')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_student_member', models.NullBooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('initial_rating', models.IntegerField(default=1200)),
                ('is_active', models.BooleanField(default=True)),
                ('ladder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Ladder')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=3, max_digits=7)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('game', models.ForeignKey(blank=True, help_text='The game associated with this rating change.', null=True, on_delete=django.db.models.deletion.CASCADE, to='club.Game')),
                ('ladder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Ladder')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='black',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black', to='club.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='ladder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Ladder'),
        ),
        migrations.AddField(
            model_name='game',
            name='white',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white', to='club.Player'),
        ),
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together=set([('player', 'ladder')]),
        ),
    ]
