# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 16:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_pgjson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('formula', models.CharField(max_length=100)),
                ('params', django_pgjson.fields.JsonBField(blank=True, default={})),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white_rating', models.IntegerField(blank=True, null=True)),
                ('black_rating', models.IntegerField(blank=True, null=True)),
                ('time_control', models.CharField(max_length=25)),
                ('result', models.SmallIntegerField(choices=[(0, '1-0'), (1, '0-1'), (2, '1/2-1/2')])),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('round', models.SmallIntegerField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'public'), (1, 'private')])),
                ('eco', models.CharField(blank=True, max_length=50, null=True)),
                ('pgn', models.CharField(blank=True, max_length=2500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ladder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('inactivity_period', models.IntegerField(blank=True, help_text="After this many days without a game, the player's ranking will drop by demotion_inc places.", null=True)),
                ('demotion_inc', models.IntegerField(blank=True, help_text="When the inactivity penalty is enforced, the player's ranking falls this many places", null=True)),
                ('rating_algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Algorithm')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_student_member', models.NullBooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('initial_rating', models.IntegerField(default=1200)),
                ('is_active', models.BooleanField(default=True)),
                ('ladder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Ladder')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('timestamp', models.DateTimeField(blank=True)),
                ('ladder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Ladder')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='black',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black', to='club.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='ladder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Ladder'),
        ),
        migrations.AddField(
            model_name='game',
            name='white',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white', to='club.Player'),
        ),
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together=set([('player', 'ladder')]),
        ),
    ]
