# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 20:48
from __future__ import unicode_literals

from django.db import migrations
import django_pgjson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='params',
            field=django_pgjson.fields.JsonBField(blank=True, default={}),
        ),
    ]
