# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_student_member',
        ),
        migrations.AddField(
            model_name='player',
            name='bio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='membership',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'unconfirmed'), (1, 'non-student member'), (2, 'student member')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='visible',
            field=models.NullBooleanField(default=True),
        ),
    ]
