# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20160317_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ladder',
            name='name',
            field=models.CharField(max_length=75),
        ),
    ]
