# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20160219_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.SmallIntegerField(choices=[(0, 'Tournament'), (1, 'Ladder')]),
        ),
        migrations.AlterField(
            model_name='game',
            name='result',
            field=models.SmallIntegerField(choices=[(0, '1-0'), (1, '0-1'), (2, '1/2-1/2')]),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'public'), (1, 'private')]),
        ),
    ]
