# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20160317_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='visible',
            field=models.SmallIntegerField(choices=[(0, 'public'), (1, 'private')], default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.SmallIntegerField(choices=[(-2, 'black disputes'), (-1, 'white disputes'), (0, 'withdrawn'), (1, 'white affirms'), (2, 'black affirms'), (3, 'confirmed')]),
        ),
    ]
