# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20160326_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='initial_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.SmallIntegerField(choices=[(-2, 'black disputes'), (-1, 'white disputes'), (0, 'withdrawn'), (1, 'white affirms'), (2, 'black affirms'), (3, 'confirmed'), (4, 'processed')]),
        ),
    ]
