# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20160219_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='demotion_inc',
            field=models.IntegerField(blank=True, help_text="When the inactivity penalty is enforced, the player's ranking falls this many places", null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='inactivity_period',
            field=models.IntegerField(blank=True, help_text="After this many days without a game, the player's ranking will drop by demotion_inc places.", null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
