# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_auto_20160226_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
