# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_auto_20160226_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='formula',
        ),
        migrations.AddField(
            model_name='algorithm',
            name='method',
            field=models.CharField(help_text='The name of the method used in rating_algs.py', max_length=30, null=True),
        ),
    ]
