# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_remove_ladder_event_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='Ranking',
        ),
    ]
