# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_auto_20160229_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='game',
            field=models.ForeignKey(blank=True, help_text='The game associated with this rating change.', null=True, on_delete=django.db.models.deletion.CASCADE, to='club.Game'),
        ),
    ]
