# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_auto_20160224_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('timestamp', models.DateTimeField(blank=True)),
                ('ladder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Ladder')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Player')),
            ],
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='rating',
        ),
    ]
