# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_rating_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladder',
            name='ladder_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'ladder'), (1, 'tournament')], null=True),
        ),
    ]
