# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_ladder_ladder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladder',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
